### ISSUE TITLE
no css files installed

### ISSUE THREAD

**Issue by barbalex** [noeldelgado/react-gemini-scrollbar#11]
I did

```
npm install react-gemini-scrollbar --save
```

then found no `node_modules/react-gemini-scrollbar/node_modules/gemini-scrollbar/gemini-scrollbar.css`

In fact, there is no `node_modules/react-gemini-scrollbar/node_modules` folder and no css files anywhere.

**Comment by barbalex** [comment]
got it:

I needed to

```
npm install --save gemini-scrollbar
```

separately. Then

```
@import '../../node_modules/gemini-scrollbar/gemini-scrollbar.css'
```

Nice tool! Thanks!

**Comment by noeldelgado** [comment]
I think it was due to the `npm` version (guessing npm@3).

I just updated the readme indicating how to resolve the stylesheet path depending on the `npm` version being used, I think that will do it for now.

Thanks @barbalex!
