### ISSUE TITLE
Every rerender component gmini container add 17px

### ISSUE THREAD

**Issue by victorpavlenko** [noeldelgado/react-gemini-scrollbar#14]
GeminiScrollbar.prototype.update = function update() {
        this._viewElement.style.width = ((this.element.offsetWidth + SCROLLBAR_WIDTH).toString() + 'px');
        this._viewElement.style.height = ((this.element.offsetHeight + SCROLLBAR_WIDTH).toString() + 'px');

Error this. Add SCROLLBAR_WIDTH 17px every state change

**Comment by noeldelgado** [comment]
Hi Victor, can you provide a small test case please (http://jsfiddle.net, http://jsbin.com/, http://codepen.io/, etc). Or if not possible, can you provide a link to a live version of your application/prototype?

I've been trying to replicate it but no luck so far.

Thanks.

**Comment by victorpavlenko** [comment]
Hi. I create PR but later

**Comment by victorpavlenko** [comment]
@noeldelgado hi i cannot fix, 
What information can I give?
Unfortunately I can not show project

**Comment by noeldelgado** [comment]
How are you defining the height of your scrollbar-container? are you using flexbox? percentages, em, vw, vh, vmin, vmax,  or any other css unit?

**Comment by victorpavlenko** [comment]
I define the height in pixels. If you have **teamviewer** I could give you access and demonstrate when there is a problem.

Leave contacts with Skype to contact you, or something like that
