### ISSUE TITLE
React 15.2.0 and unknown props

### ISSUE THREAD

**Issue by vdh** [noeldelgado/react-gemini-scrollbar#25]
React 15.2 added some (rather obtuse) [warning messages about unknown props](https://fb.me/react-unknown-prop):

```
Warning: Unknown props `autoshow`, `forceGemini` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by GeminiScrollbar)
```

**Comment by vdh** [comment]
@noeldelgado I didn't make any changes in #26 to `dist/index.js`, I only touched `src/index.jsx`, so it'll need a rebuild.

**Comment by noeldelgado** [comment]
@vdh, are you sure? I didn't test it, but I checked the build and didn't find any reference to `autoshow` or `forceGemini` on the `render` method. I will make a quick test though.

**Comment by vdh** [comment]
@noeldelgado I created #27 to rebuild the fix into `dist/index.js`.
