### ISSUE TITLE
React Deprecation warnings

### ISSUE THREAD

**Issue by woodsct** [noeldelgado/react-gemini-scrollbar#34]
I'm getting two react deprecation warning:
> React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement

> Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead

In the latest version of React these warnings were added can you upgrade to conform to the new standards?

**Comment by akhar** [comment]
And now this one can be closed.

**Comment by noeldelgado** [comment]
Thanks @akhar 👍 
@woodsct can you confirm and close please?

**Comment by woodsct** [comment]
Yup all fixed now thanks
