### ISSUE TITLE
Not working, always showing OS scrollbar

### ISSUE THREAD

**Issue by asso1985** [noeldelgado/react-gemini-scrollbar#5]

**Comment by noeldelgado** [comment]
Can you include system details (browser, OS, versions)?
If using OS X `System Preferences » General » Show scroll bar`?
Any link to a demo recreating the problem? ([JS Bin](http://jsbin.com/), [JSFiddle](https://jsfiddle.net/), [Codepen](http://codepen.io/), etc)

thanks

**Comment by noeldelgado** [comment]
@asso1985 Any chance you are missing gemini's css file?

**Comment by asso1985** [comment]
I was mistaking, you should highlight in the docs the fact that in OSX the plugin won't start. Wich is cool anyway. Sorry
