### ISSUE TITLE
onScroll event 

### ISSUE THREAD

**Issue by ponty96** [noeldelgado/react-gemini-scrollbar#8]
does the scroll bar have an onScroll event or an onScrollToBottom event? if it does what are the values passed?

**Comment by noeldelgado** [comment]
Hi, nope, it does not have an 'onScroll' (or similar) event. 

However, you can access the scrollable-element node via the `...scrollbar.getViewElement()` method and register to any event handler you need.

**Comment by ponty96** [comment]
okay thanks. but i think you should consider adding an onScroll event
